// Generated by scripts/gen-types.ts on 2026-09-12T00:22:11.599Z - do not edit by hand.
// Run: npm run gen:types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      _migrations: {
        Row: {
          applied_at: string
          id: number
          name: string
        }
        Insert: {
          applied_at?: string
          id?: number
          name: string
        }
        Update: {
          applied_at?: string
          id?: number
          name?: string
        }
        Relationships: []
      }
      addresses: {
        Row: {
          area: string | null
          created_at: string
          customer_id: string
          district: string | null
          division: string | null
          id: string
          is_default: boolean
          landmark: string | null
          phone: string | null
          postcode: string | null
          recipient_name: string | null
          street_address: string
          upazila: string | null
          updated_at: string
        }
        Insert: {
          area?: string | null
          created_at?: string
          customer_id: string
          district?: string | null
          division?: string | null
          id?: string
          is_default?: boolean
          landmark?: string | null
          phone?: string | null
          postcode?: string | null
          recipient_name?: string | null
          street_address: string
          upazila?: string | null
          updated_at?: string
        }
        Update: {
          area?: string | null
          created_at?: string
          customer_id?: string
          district?: string | null
          division?: string | null
          id?: string
          is_default?: boolean
          landmark?: string | null
          phone?: string | null
          postcode?: string | null
          recipient_name?: string | null
          street_address?: string
          upazila?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "addresses_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_users: {
        Row: {
          created_at: string
          email: string | null
          full_name: string | null
          id: string
          is_active: boolean
          last_login_at: string | null
          role: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          full_name?: string | null
          id: string
          is_active?: boolean
          last_login_at?: string | null
          role?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string | null
          full_name?: string | null
          id?: string
          is_active?: boolean
          last_login_at?: string | null
          role?: string
          updated_at?: string
        }
        Relationships: []
      }
      audit_log: {
        Row: {
          action: string
          actor_email: string | null
          actor_id: string | null
          after: Json | null
          before: Json | null
          created_at: string
          entity_id: string | null
          entity_type: string | null
          id: string
          ip: unknown
          updated_at: string
        }
        Insert: {
          action: string
          actor_email?: string | null
          actor_id?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          entity_id?: string | null
          entity_type?: string | null
          id?: string
          ip?: unknown
          updated_at?: string
        }
        Update: {
          action?: string
          actor_email?: string | null
          actor_id?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          entity_id?: string | null
          entity_type?: string | null
          id?: string
          ip?: unknown
          updated_at?: string
        }
        Relationships: []
      }
      bd_locations: {
        Row: {
          created_at: string
          id: string
          level: string
          name_bn: string | null
          name_en: string
          parent_id: string | null
          position: number
          slug: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          level: string
          name_bn?: string | null
          name_en: string
          parent_id?: string | null
          position?: number
          slug: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          level?: string
          name_bn?: string | null
          name_en?: string
          parent_id?: string | null
          position?: number
          slug?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "bd_locations_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "bd_locations"
            referencedColumns: ["id"]
          },
        ]
      }
      brands: {
        Row: {
          created_at: string
          id: string
          is_active: boolean
          logo_url: string | null
          name: string
          slug: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_active?: boolean
          logo_url?: string | null
          name: string
          slug: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          is_active?: boolean
          logo_url?: string | null
          name?: string
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      cart_items: {
        Row: {
          cart_id: string
          created_at: string
          id: string
          quantity: number
          updated_at: string
          variant_id: string
        }
        Insert: {
          cart_id: string
          created_at?: string
          id?: string
          quantity: number
          updated_at?: string
          variant_id: string
        }
        Update: {
          cart_id?: string
          created_at?: string
          id?: string
          quantity?: number
          updated_at?: string
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "cart_items_cart_id_fkey"
            columns: ["cart_id"]
            isOneToOne: false
            referencedRelation: "carts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cart_items_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cart_items_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants_public"
            referencedColumns: ["id"]
          },
        ]
      }
      carts: {
        Row: {
          created_at: string
          customer_id: string | null
          expires_at: string
          id: string
          session_token: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          customer_id?: string | null
          expires_at?: string
          id?: string
          session_token: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          customer_id?: string | null
          expires_at?: string
          id?: string
          session_token?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "carts_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          created_at: string
          description_bn: string | null
          description_en: string | null
          id: string
          image_url: string | null
          is_active: boolean
          name_bn: string | null
          name_en: string
          parent_id: string | null
          position: number
          slug: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description_bn?: string | null
          description_en?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          name_bn?: string | null
          name_en: string
          parent_id?: string | null
          position?: number
          slug: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description_bn?: string | null
          description_en?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          name_bn?: string | null
          name_en?: string
          parent_id?: string | null
          position?: number
          slug?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "categories_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      collection_products: {
        Row: {
          collection_id: string
          created_at: string
          position: number
          product_id: string
          updated_at: string
        }
        Insert: {
          collection_id: string
          created_at?: string
          position?: number
          product_id: string
          updated_at?: string
        }
        Update: {
          collection_id?: string
          created_at?: string
          position?: number
          product_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "collection_products_collection_id_fkey"
            columns: ["collection_id"]
            isOneToOne: false
            referencedRelation: "collections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "collection_products_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "collection_products_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_public"
            referencedColumns: ["id"]
          },
        ]
      }
      collections: {
        Row: {
          created_at: string
          description_en: string | null
          id: string
          image_url: string | null
          is_active: boolean
          is_automatic: boolean
          position: number
          rules: Json | null
          slug: string
          title_bn: string | null
          title_en: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description_en?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          is_automatic?: boolean
          position?: number
          rules?: Json | null
          slug: string
          title_bn?: string | null
          title_en: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description_en?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          is_automatic?: boolean
          position?: number
          rules?: Json | null
          slug?: string
          title_bn?: string | null
          title_en?: string
          updated_at?: string
        }
        Relationships: []
      }
      coupon_redemptions: {
        Row: {
          coupon_id: string
          created_at: string
          customer_id: string | null
          discount_bdt: number
          id: string
          order_id: string
          updated_at: string
        }
        Insert: {
          coupon_id: string
          created_at?: string
          customer_id?: string | null
          discount_bdt?: number
          id?: string
          order_id: string
          updated_at?: string
        }
        Update: {
          coupon_id?: string
          created_at?: string
          customer_id?: string | null
          discount_bdt?: number
          id?: string
          order_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "coupon_redemptions_coupon_id_fkey"
            columns: ["coupon_id"]
            isOneToOne: false
            referencedRelation: "coupons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "coupon_redemptions_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "coupon_redemptions_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      coupons: {
        Row: {
          applies_to: Json
          code: string
          created_at: string
          description: string | null
          ends_at: string | null
          id: string
          is_active: boolean
          max_discount_bdt: number | null
          min_order_bdt: number
          starts_at: string | null
          times_used: number
          type: string
          updated_at: string
          usage_limit: number | null
          usage_limit_per_customer: number
          value: number
        }
        Insert: {
          applies_to?: Json
          code: string
          created_at?: string
          description?: string | null
          ends_at?: string | null
          id?: string
          is_active?: boolean
          max_discount_bdt?: number | null
          min_order_bdt?: number
          starts_at?: string | null
          times_used?: number
          type: string
          updated_at?: string
          usage_limit?: number | null
          usage_limit_per_customer?: number
          value?: number
        }
        Update: {
          applies_to?: Json
          code?: string
          created_at?: string
          description?: string | null
          ends_at?: string | null
          id?: string
          is_active?: boolean
          max_discount_bdt?: number | null
          min_order_bdt?: number
          starts_at?: string | null
          times_used?: number
          type?: string
          updated_at?: string
          usage_limit?: number | null
          usage_limit_per_customer?: number
          value?: number
        }
        Relationships: []
      }
      courier_api_log: {
        Row: {
          courier_code: string
          created_at: string
          duration_ms: number | null
          endpoint: string
          error: string | null
          id: string
          method: string
          request: Json | null
          response: Json | null
          status_code: number | null
          updated_at: string
        }
        Insert: {
          courier_code: string
          created_at?: string
          duration_ms?: number | null
          endpoint: string
          error?: string | null
          id?: string
          method: string
          request?: Json | null
          response?: Json | null
          status_code?: number | null
          updated_at?: string
        }
        Update: {
          courier_code?: string
          created_at?: string
          duration_ms?: number | null
          endpoint?: string
          error?: string | null
          id?: string
          method?: string
          request?: Json | null
          response?: Json | null
          status_code?: number | null
          updated_at?: string
        }
        Relationships: []
      }
      courier_score_cache: {
        Row: {
          checked_at: string
          courier_code: string
          created_at: string
          expires_at: string
          fraud_report_count: number
          phone: string
          raw: Json | null
          success_ratio: number | null
          total_cancelled: number
          total_delivered: number
          total_parcels: number
          updated_at: string
        }
        Insert: {
          checked_at?: string
          courier_code: string
          created_at?: string
          expires_at?: string
          fraud_report_count?: number
          phone: string
          raw?: Json | null
          success_ratio?: number | null
          total_cancelled?: number
          total_delivered?: number
          total_parcels?: number
          updated_at?: string
        }
        Update: {
          checked_at?: string
          courier_code?: string
          created_at?: string
          expires_at?: string
          fraud_report_count?: number
          phone?: string
          raw?: Json | null
          success_ratio?: number | null
          total_cancelled?: number
          total_delivered?: number
          total_parcels?: number
          updated_at?: string
        }
        Relationships: []
      }
      couriers: {
        Row: {
          code: string
          config: Json
          created_at: string
          id: string
          is_active: boolean
          is_default: boolean
          name: string
          supported_districts: string[]
          updated_at: string
        }
        Insert: {
          code: string
          config?: Json
          created_at?: string
          id?: string
          is_active?: boolean
          is_default?: boolean
          name: string
          supported_districts?: string[]
          updated_at?: string
        }
        Update: {
          code?: string
          config?: Json
          created_at?: string
          id?: string
          is_active?: boolean
          is_default?: boolean
          name?: string
          supported_districts?: string[]
          updated_at?: string
        }
        Relationships: []
      }
      customers: {
        Row: {
          block_reason: string | null
          created_at: string
          email: string | null
          full_name: string | null
          id: string
          is_blocked: boolean
          notes: string | null
          phone: string
          total_cancelled: number
          total_delivered: number
          total_orders: number
          total_returned: number
          updated_at: string
        }
        Insert: {
          block_reason?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id: string
          is_blocked?: boolean
          notes?: string | null
          phone: string
          total_cancelled?: number
          total_delivered?: number
          total_orders?: number
          total_returned?: number
          updated_at?: string
        }
        Update: {
          block_reason?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id?: string
          is_blocked?: boolean
          notes?: string | null
          phone?: string
          total_cancelled?: number
          total_delivered?: number
          total_orders?: number
          total_returned?: number
          updated_at?: string
        }
        Relationships: []
      }
      demo_settings: {
        Row: {
          created_at: string
          key: string
          updated_at: string
          value: Json
        }
        Insert: {
          created_at?: string
          key: string
          updated_at?: string
          value: Json
        }
        Update: {
          created_at?: string
          key?: string
          updated_at?: string
          value?: Json
        }
        Relationships: []
      }
      demo_sms_log: {
        Row: {
          created_at: string
          error: string | null
          id: string
          kind: string
          message: string
          provider: string
          provider_ref: string | null
          sent_at: string
          status: string
          to_phone: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          error?: string | null
          id?: string
          kind: string
          message: string
          provider?: string
          provider_ref?: string | null
          sent_at?: string
          status?: string
          to_phone: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          error?: string | null
          id?: string
          kind?: string
          message?: string
          provider?: string
          provider_ref?: string | null
          sent_at?: string
          status?: string
          to_phone?: string
          updated_at?: string
        }
        Relationships: []
      }
      order_events: {
        Row: {
          actor_id: string | null
          actor_type: string
          created_at: string
          event_type: string
          from_status: string | null
          id: string
          metadata: Json | null
          note: string | null
          order_id: string
          to_status: string | null
          updated_at: string
        }
        Insert: {
          actor_id?: string | null
          actor_type?: string
          created_at?: string
          event_type: string
          from_status?: string | null
          id?: string
          metadata?: Json | null
          note?: string | null
          order_id: string
          to_status?: string | null
          updated_at?: string
        }
        Update: {
          actor_id?: string | null
          actor_type?: string
          created_at?: string
          event_type?: string
          from_status?: string | null
          id?: string
          metadata?: Json | null
          note?: string | null
          order_id?: string
          to_status?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_events_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          created_at: string
          id: string
          image_url: string | null
          line_total_bdt: number
          order_id: string
          product_id: string | null
          product_title: string
          quantity: number
          sku: string | null
          unit_price_bdt: number
          updated_at: string
          variant_id: string | null
          variant_label: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          image_url?: string | null
          line_total_bdt: number
          order_id: string
          product_id?: string | null
          product_title: string
          quantity: number
          sku?: string | null
          unit_price_bdt: number
          updated_at?: string
          variant_id?: string | null
          variant_label?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          image_url?: string | null
          line_total_bdt?: number
          order_id?: string
          product_id?: string | null
          product_title?: string
          quantity?: number
          sku?: string | null
          unit_price_bdt?: number
          updated_at?: string
          variant_id?: string | null
          variant_label?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants_public"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          admin_note: string | null
          cancelled_at: string | null
          confirmed_at: string | null
          coupon_code: string | null
          coupon_id: string | null
          courier: string | null
          courier_response: Json | null
          created_at: string
          customer_email: string | null
          customer_id: string | null
          customer_name: string | null
          customer_note: string | null
          customer_phone: string
          delivered_at: string | null
          discount_bdt: number
          fraud_flags: Json
          fraud_score: number | null
          id: string
          ip: unknown
          is_phone_verified: boolean
          landing_page: string | null
          needs_review: boolean
          order_number: string
          payment_method: string
          payment_status: string
          placed_at: string
          referrer: string | null
          shipped_at: string | null
          shipping_address: Json
          shipping_bdt: number
          status: string
          subtotal_bdt: number
          total_bdt: number
          tracking_id: string | null
          updated_at: string
          utm_campaign: string | null
          utm_medium: string | null
          utm_source: string | null
        }
        Insert: {
          admin_note?: string | null
          cancelled_at?: string | null
          confirmed_at?: string | null
          coupon_code?: string | null
          coupon_id?: string | null
          courier?: string | null
          courier_response?: Json | null
          created_at?: string
          customer_email?: string | null
          customer_id?: string | null
          customer_name?: string | null
          customer_note?: string | null
          customer_phone: string
          delivered_at?: string | null
          discount_bdt?: number
          fraud_flags?: Json
          fraud_score?: number | null
          id?: string
          ip?: unknown
          is_phone_verified?: boolean
          landing_page?: string | null
          needs_review?: boolean
          order_number: string
          payment_method: string
          payment_status?: string
          placed_at?: string
          referrer?: string | null
          shipped_at?: string | null
          shipping_address: Json
          shipping_bdt?: number
          status?: string
          subtotal_bdt?: number
          total_bdt?: number
          tracking_id?: string | null
          updated_at?: string
          utm_campaign?: string | null
          utm_medium?: string | null
          utm_source?: string | null
        }
        Update: {
          admin_note?: string | null
          cancelled_at?: string | null
          confirmed_at?: string | null
          coupon_code?: string | null
          coupon_id?: string | null
          courier?: string | null
          courier_response?: Json | null
          created_at?: string
          customer_email?: string | null
          customer_id?: string | null
          customer_name?: string | null
          customer_note?: string | null
          customer_phone?: string
          delivered_at?: string | null
          discount_bdt?: number
          fraud_flags?: Json
          fraud_score?: number | null
          id?: string
          ip?: unknown
          is_phone_verified?: boolean
          landing_page?: string | null
          needs_review?: boolean
          order_number?: string
          payment_method?: string
          payment_status?: string
          placed_at?: string
          referrer?: string | null
          shipped_at?: string | null
          shipping_address?: Json
          shipping_bdt?: number
          status?: string
          subtotal_bdt?: number
          total_bdt?: number
          tracking_id?: string | null
          updated_at?: string
          utm_campaign?: string | null
          utm_medium?: string | null
          utm_source?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "orders_coupon_id_fkey"
            columns: ["coupon_id"]
            isOneToOne: false
            referencedRelation: "coupons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      otp_codes: {
        Row: {
          attempts: number
          code_hash: string
          consumed_at: string | null
          created_at: string
          expires_at: string
          id: string
          ip: unknown
          phone: string
          updated_at: string
          user_agent: string | null
        }
        Insert: {
          attempts?: number
          code_hash: string
          consumed_at?: string | null
          created_at?: string
          expires_at: string
          id?: string
          ip?: unknown
          phone: string
          updated_at?: string
          user_agent?: string | null
        }
        Update: {
          attempts?: number
          code_hash?: string
          consumed_at?: string | null
          created_at?: string
          expires_at?: string
          id?: string
          ip?: unknown
          phone?: string
          updated_at?: string
          user_agent?: string | null
        }
        Relationships: []
      }
      payment_transactions: {
        Row: {
          amount_bdt: number
          bank_txn_id: string | null
          card_issuer: string | null
          card_type: string | null
          created_at: string
          currency: string
          gateway: string
          gateway_txn_id: string | null
          id: string
          order_id: string
          raw_initiate_response: Json | null
          raw_ipn_payload: Json | null
          raw_validation_response: Json | null
          status: string
          updated_at: string
          val_id: string | null
          validated_at: string | null
        }
        Insert: {
          amount_bdt: number
          bank_txn_id?: string | null
          card_issuer?: string | null
          card_type?: string | null
          created_at?: string
          currency?: string
          gateway?: string
          gateway_txn_id?: string | null
          id?: string
          order_id: string
          raw_initiate_response?: Json | null
          raw_ipn_payload?: Json | null
          raw_validation_response?: Json | null
          status?: string
          updated_at?: string
          val_id?: string | null
          validated_at?: string | null
        }
        Update: {
          amount_bdt?: number
          bank_txn_id?: string | null
          card_issuer?: string | null
          card_type?: string | null
          created_at?: string
          currency?: string
          gateway?: string
          gateway_txn_id?: string | null
          id?: string
          order_id?: string
          raw_initiate_response?: Json | null
          raw_ipn_payload?: Json | null
          raw_validation_response?: Json | null
          status?: string
          updated_at?: string
          val_id?: string | null
          validated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "payment_transactions_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      product_categories: {
        Row: {
          category_id: string
          created_at: string
          product_id: string
          updated_at: string
        }
        Insert: {
          category_id: string
          created_at?: string
          product_id: string
          updated_at?: string
        }
        Update: {
          category_id?: string
          created_at?: string
          product_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_categories_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_categories_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_categories_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_public"
            referencedColumns: ["id"]
          },
        ]
      }
      product_images: {
        Row: {
          alt_text_bn: string | null
          alt_text_en: string
          blur_data_url: string | null
          bytes: number | null
          content_hash: string | null
          created_at: string
          format: string | null
          height: number | null
          id: string
          manifest: Json | null
          position: number
          product_id: string
          updated_at: string
          url: string
          variant_id: string | null
          width: number | null
        }
        Insert: {
          alt_text_bn?: string | null
          alt_text_en: string
          blur_data_url?: string | null
          bytes?: number | null
          content_hash?: string | null
          created_at?: string
          format?: string | null
          height?: number | null
          id?: string
          manifest?: Json | null
          position?: number
          product_id: string
          updated_at?: string
          url: string
          variant_id?: string | null
          width?: number | null
        }
        Update: {
          alt_text_bn?: string | null
          alt_text_en?: string
          blur_data_url?: string | null
          bytes?: number | null
          content_hash?: string | null
          created_at?: string
          format?: string | null
          height?: number | null
          id?: string
          manifest?: Json | null
          position?: number
          product_id?: string
          updated_at?: string
          url?: string
          variant_id?: string | null
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "product_images_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_images_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_public"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_images_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_images_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants_public"
            referencedColumns: ["id"]
          },
        ]
      }
      product_variants: {
        Row: {
          compare_at_price_bdt: number | null
          cost_bdt: number | null
          created_at: string
          id: string
          is_default: boolean
          low_stock_threshold: number
          option_name: string | null
          option_value: string | null
          position: number
          price_bdt: number
          product_id: string
          sku: string
          stock_qty: number
          updated_at: string
          weight_grams: number | null
        }
        Insert: {
          compare_at_price_bdt?: number | null
          cost_bdt?: number | null
          created_at?: string
          id?: string
          is_default?: boolean
          low_stock_threshold?: number
          option_name?: string | null
          option_value?: string | null
          position?: number
          price_bdt: number
          product_id: string
          sku: string
          stock_qty?: number
          updated_at?: string
          weight_grams?: number | null
        }
        Update: {
          compare_at_price_bdt?: number | null
          cost_bdt?: number | null
          created_at?: string
          id?: string
          is_default?: boolean
          low_stock_threshold?: number
          option_name?: string | null
          option_value?: string | null
          position?: number
          price_bdt?: number
          product_id?: string
          sku?: string
          stock_qty?: number
          updated_at?: string
          weight_grams?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "product_variants_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_variants_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_public"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          brand_id: string | null
          created_at: string
          description_bn: string | null
          description_en: string | null
          highlights: string[]
          id: string
          is_featured: boolean
          published_at: string | null
          search_vector: unknown
          short_description: string | null
          slug: string
          specs: Json
          status: string
          title_bn: string | null
          title_en: string
          updated_at: string
          video_url: string | null
          warranty_months: number
        }
        Insert: {
          brand_id?: string | null
          created_at?: string
          description_bn?: string | null
          description_en?: string | null
          highlights?: string[]
          id?: string
          is_featured?: boolean
          published_at?: string | null
          search_vector?: unknown
          short_description?: string | null
          slug: string
          specs?: Json
          status?: string
          title_bn?: string | null
          title_en: string
          updated_at?: string
          video_url?: string | null
          warranty_months?: number
        }
        Update: {
          brand_id?: string | null
          created_at?: string
          description_bn?: string | null
          description_en?: string | null
          highlights?: string[]
          id?: string
          is_featured?: boolean
          published_at?: string | null
          search_vector?: unknown
          short_description?: string | null
          slug?: string
          specs?: Json
          status?: string
          title_bn?: string | null
          title_en?: string
          updated_at?: string
          video_url?: string | null
          warranty_months?: number
        }
        Relationships: [
          {
            foreignKeyName: "products_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brands"
            referencedColumns: ["id"]
          },
        ]
      }
      reviews: {
        Row: {
          admin_reply: string | null
          body: string | null
          created_at: string
          customer_id: string | null
          id: string
          is_verified_purchase: boolean
          order_id: string | null
          product_id: string
          rating: number
          replied_at: string | null
          reviewer_name: string | null
          status: string
          title: string | null
          updated_at: string
        }
        Insert: {
          admin_reply?: string | null
          body?: string | null
          created_at?: string
          customer_id?: string | null
          id?: string
          is_verified_purchase?: boolean
          order_id?: string | null
          product_id: string
          rating: number
          replied_at?: string | null
          reviewer_name?: string | null
          status?: string
          title?: string | null
          updated_at?: string
        }
        Update: {
          admin_reply?: string | null
          body?: string | null
          created_at?: string
          customer_id?: string | null
          id?: string
          is_verified_purchase?: boolean
          order_id?: string | null
          product_id?: string
          rating?: number
          replied_at?: string | null
          reviewer_name?: string | null
          status?: string
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "reviews_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_public"
            referencedColumns: ["id"]
          },
        ]
      }
      shipments: {
        Row: {
          cod_amount_bdt: number
          consignment_id: string | null
          courier_code: string
          created_at: string
          delivered_at: string | null
          delivery_charge_bdt: number | null
          dispatched_at: string | null
          id: string
          invoice_ref: string | null
          last_polled_at: string | null
          last_webhook_payload: Json | null
          next_transition_at: string | null
          normalized_status: string
          note: string | null
          order_id: string
          raw_create_response: Json | null
          status: string | null
          tracking_code: string | null
          updated_at: string
        }
        Insert: {
          cod_amount_bdt?: number
          consignment_id?: string | null
          courier_code: string
          created_at?: string
          delivered_at?: string | null
          delivery_charge_bdt?: number | null
          dispatched_at?: string | null
          id?: string
          invoice_ref?: string | null
          last_polled_at?: string | null
          last_webhook_payload?: Json | null
          next_transition_at?: string | null
          normalized_status?: string
          note?: string | null
          order_id: string
          raw_create_response?: Json | null
          status?: string | null
          tracking_code?: string | null
          updated_at?: string
        }
        Update: {
          cod_amount_bdt?: number
          consignment_id?: string | null
          courier_code?: string
          created_at?: string
          delivered_at?: string | null
          delivery_charge_bdt?: number | null
          dispatched_at?: string | null
          id?: string
          invoice_ref?: string | null
          last_polled_at?: string | null
          last_webhook_payload?: Json | null
          next_transition_at?: string | null
          normalized_status?: string
          note?: string | null
          order_id?: string
          raw_create_response?: Json | null
          status?: string | null
          tracking_code?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "shipments_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      shipping_rates: {
        Row: {
          created_at: string
          estimated_days: string | null
          free_above_bdt: number | null
          id: string
          name: string
          position: number
          rate_bdt: number
          updated_at: string
          zone_id: string
        }
        Insert: {
          created_at?: string
          estimated_days?: string | null
          free_above_bdt?: number | null
          id?: string
          name: string
          position?: number
          rate_bdt: number
          updated_at?: string
          zone_id: string
        }
        Update: {
          created_at?: string
          estimated_days?: string | null
          free_above_bdt?: number | null
          id?: string
          name?: string
          position?: number
          rate_bdt?: number
          updated_at?: string
          zone_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "shipping_rates_zone_id_fkey"
            columns: ["zone_id"]
            isOneToOne: false
            referencedRelation: "shipping_zones"
            referencedColumns: ["id"]
          },
        ]
      }
      shipping_zones: {
        Row: {
          created_at: string
          districts: string[]
          id: string
          is_active: boolean
          name: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          districts?: string[]
          id?: string
          is_active?: boolean
          name: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          districts?: string[]
          id?: string
          is_active?: boolean
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      stock_movements: {
        Row: {
          actor_id: string | null
          created_at: string
          delta: number
          id: string
          note: string | null
          order_id: string | null
          reason: string
          updated_at: string
          variant_id: string
        }
        Insert: {
          actor_id?: string | null
          created_at?: string
          delta: number
          id?: string
          note?: string | null
          order_id?: string | null
          reason: string
          updated_at?: string
          variant_id: string
        }
        Update: {
          actor_id?: string | null
          created_at?: string
          delta?: number
          id?: string
          note?: string | null
          order_id?: string | null
          reason?: string
          updated_at?: string
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "stock_movements_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_movements_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_movements_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants_public"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      product_variants_public: {
        Row: {
          compare_at_price_bdt: number | null
          created_at: string | null
          id: string | null
          is_default: boolean | null
          low_stock_threshold: number | null
          option_name: string | null
          option_value: string | null
          position: number | null
          price_bdt: number | null
          product_id: string | null
          sku: string | null
          stock_qty: number | null
          updated_at: string | null
          weight_grams: number | null
        }
        Insert: {
          compare_at_price_bdt?: number | null
          created_at?: string | null
          id?: string | null
          is_default?: boolean | null
          low_stock_threshold?: number | null
          option_name?: string | null
          option_value?: string | null
          position?: number | null
          price_bdt?: number | null
          product_id?: string | null
          sku?: string | null
          stock_qty?: number | null
          updated_at?: string | null
          weight_grams?: number | null
        }
        Update: {
          compare_at_price_bdt?: number | null
          created_at?: string | null
          id?: string | null
          is_default?: boolean | null
          low_stock_threshold?: number | null
          option_name?: string | null
          option_value?: string | null
          position?: number | null
          price_bdt?: number | null
          product_id?: string | null
          sku?: string | null
          stock_qty?: number | null
          updated_at?: string | null
          weight_grams?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "product_variants_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_variants_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_public"
            referencedColumns: ["id"]
          },
        ]
      }
      products_public: {
        Row: {
          brand_id: string | null
          brand_name: string | null
          brand_slug: string | null
          created_at: string | null
          description_bn: string | null
          description_en: string | null
          highlights: string[] | null
          id: string | null
          is_featured: boolean | null
          max_compare_at_price_bdt: number | null
          max_price_bdt: number | null
          min_price_bdt: number | null
          primary_image_alt: string | null
          primary_image_url: string | null
          published_at: string | null
          short_description: string | null
          slug: string | null
          specs: Json | null
          status: string | null
          title_bn: string | null
          title_en: string | null
          total_stock: number | null
          updated_at: string | null
          variant_count: number | null
          video_url: string | null
          warranty_months: number | null
        }
        Relationships: [
          {
            foreignKeyName: "products_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brands"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      admin_role: { Args: never; Returns: string }
      apply_updated_at: { Args: { tbl: unknown }; Returns: undefined }
      demo_counts: { Args: never; Returns: Json }
      demo_shift_clock: { Args: { days: number }; Returns: number }
      demo_truncate_all: { Args: never; Returns: undefined }
      demo_truncate_transactional: { Args: never; Returns: undefined }
      immutable_array_to_string: {
        Args: { arr: string[]; sep: string }
        Returns: string
      }
      is_admin: { Args: never; Returns: boolean }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
