/**
 * Regenerate src/lib/database.types.ts WITHOUT the Supabase CLI.
 *
 * Default: Supabase Management API
 *   GET https://api.supabase.com/v1/projects/{ref}/types/typescript
 * using SUPABASE_ACCESS_TOKEN + SUPABASE_PROJECT_REF from .env.local.
 *
 *   npm run gen:types            (Management API)
 *   npm run gen:types -- --cli   (shells out to `npx supabase gen types`; token passed via env,
 *                                 so it works in PowerShell without $VAR syntax)
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadEnv, requireEnv } from "./lib/env";

loadEnv();
const ref = requireEnv("SUPABASE_PROJECT_REF");
const token = requireEnv("SUPABASE_ACCESS_TOKEN");
const out = resolve(process.cwd(), "src/lib/database.types.ts");
mkdirSync(resolve(process.cwd(), "src/lib"), { recursive: true });

async function viaApi(): Promise<string> {
  const res = await fetch(
    `https://api.supabase.com/v1/projects/${ref}/types/typescript?included_schemas=public`,
    { headers: { Authorization: `Bearer ${token}` } },
  );
  if (!res.ok) throw new Error(`Management API ${res.status}: ${await res.text()}`);
  const json = (await res.json()) as { types: string };
  return json.types;
}

function viaCli(): string {
  const isWin = process.platform === "win32";
  const r = spawnSync(
    isWin ? "npx.cmd" : "npx",
    ["--yes", "supabase", "gen", "types", "typescript", "--project-id", ref, "--schema", "public"],
    { env: { ...process.env, SUPABASE_ACCESS_TOKEN: token }, encoding: "utf8", shell: isWin },
  );
  if (r.status !== 0) throw new Error(`supabase CLI failed: ${r.stderr}`);
  return r.stdout;
}

(async () => {
  const types = process.argv.includes("--cli") ? viaCli() : await viaApi();
  const header = `// Generated by scripts/gen-types.ts on ${new Date().toISOString()} - do not edit by hand.\n// Run: npm run gen:types\n\n`;
  writeFileSync(out, header + types.replace(/\r\n/g, "\n"));
  console.log(`Wrote src/lib/database.types.ts (${types.length} chars)`);
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
