/**
 * Generate placeholder product images (solid brand-ish colour + product name),
 * run them through the Phase 2 pipeline, and write
 * src/lib/seed/data/images.generated.ts so the seed can attach them.
 *
 *   npm run seed:images            3 images per product (skips already-ingested)
 *   npm run seed:images -- --force re-render + re-upload everything
 *
 * Replace public/seed-images/<slug>/N.png with real photos later and re-run;
 * the pipeline is identical for real photos.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import sharp from "sharp";
import { loadEnv } from "./lib/env";
import { fileHash, readImageCache, writeImageCache, type CachedImage } from "./images-ingest";

loadEnv();

const OUT_DIR = resolve(process.cwd(), "public/seed-images");
const GENERATED = resolve(process.cwd(), "src/lib/seed/data/images.generated.ts");
const PER_PRODUCT = 3;
const PALETTE = ["#1A1A1A", "#242424", "#2F2F2F", "#FFC107", "#FFD65C", "#E8A800", "#F5F5F5", "#E0E0E0", "#3B3B3B", "#6B6B6B"];

function hashStr(s: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 0x01000193) >>> 0;
  return h >>> 0;
}

function escapeXml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

async function renderPlaceholder(slug: string, title: string, index: number): Promise<Buffer> {
  const h = hashStr(`${slug}:${index}`);
  const bg = PALETTE[h % PALETTE.length];
  const dark = ["#1A1A1A", "#242424", "#2F2F2F", "#3B3B3B", "#6B6B6B"].includes(bg);
  const fg = dark ? "#FAFAFA" : "#1A1A1A";
  const accent = dark ? "#FFC107" : "#1A1A1A";
  const words = title.split(" ");
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    if ((cur + " " + w).trim().length > 22) {
      lines.push(cur.trim());
      cur = w;
    } else cur = `${cur} ${w}`;
  }
  if (cur.trim()) lines.push(cur.trim());
  const text = lines
    .slice(0, 4)
    .map((l, i) => `<text x="800" y="${700 + i * 90}" font-size="64" font-family="Arial, Helvetica, sans-serif" font-weight="600" fill="${fg}" text-anchor="middle">${escapeXml(l)}</text>`)
    .join("");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1600">
    <rect width="1600" height="1600" fill="${bg}"/>
    <rect x="${400 + (h % 200)}" y="${300 + ((h >> 4) % 120)}" width="${600 + ((h >> 8) % 300)}" height="${260 + ((h >> 12) % 120)}" rx="48" fill="${accent}" opacity="0.18"/>
    <rect x="700" y="1180" width="200" height="12" rx="6" fill="${accent}"/>
    <text x="800" y="1300" font-size="40" font-family="Arial, Helvetica, sans-serif" fill="${fg}" opacity="0.6" text-anchor="middle">PLACEHOLDER ${index + 1} / ${PER_PRODUCT}</text>
    ${text}
  </svg>`;
  return sharp(Buffer.from(svg)).png().toBuffer();
}

(async () => {
  const force = process.argv.includes("--force");
  const { PRODUCTS } = await import("../src/lib/seed/data/catalog");
  const { processAndUpload } = await import("../src/lib/media/ingest");
  const cache = readImageCache();
  const out: Record<string, (CachedImage & { alt: string })[]> = {};
  let uploaded = 0;
  let cached = 0;

  for (const p of PRODUCTS) {
    const dir = join(OUT_DIR, p.slug);
    mkdirSync(dir, { recursive: true });
    out[p.slug] = [];
    for (let i = 0; i < PER_PRODUCT; i++) {
      const file = join(dir, `${i + 1}.png`);
      if (force || !existsSync(file)) writeFileSync(file, await renderPlaceholder(p.slug, p.title_en, i));
      const buf = readFileSync(file);
      const key = fileHash(buf);
      let img = cache[key];
      if (!img || force) {
        const up = await processAndUpload(buf);
        img = { hash: up.hash, width: up.width, height: up.height, blurDataUrl: up.blurDataUrl, url: up.url, bytes: up.bytes, manifest: up.manifest };
        cache[key] = img;
        writeImageCache(cache);
        uploaded++;
        process.stdout.write(`  ${p.slug} #${i + 1} ${up.reused ? "reused" : "uploaded"}\n`);
      } else cached++;
      out[p.slug].push({ ...img, alt: `${p.title_en} - image ${i + 1}` });
    }
  }

  const ts = `/**
 * GENERATED by scripts/seed-images.ts on ${new Date().toISOString()} - do not edit by hand.
 * Product slug -> ingested placeholder images (URLs live in Supabase Storage or R2).
 */
export interface SeedImage {
  hash: string;
  width: number;
  height: number;
  blurDataUrl: string;
  url: string;
  bytes: number;
  manifest: unknown;
  alt: string;
}

export const SEED_IMAGES: Record<string, SeedImage[]> = ${JSON.stringify(out, null, 2)};
`;
  writeFileSync(GENERATED, ts);
  console.log(`\nDone: ${uploaded} uploaded, ${cached} from cache. Wrote src/lib/seed/data/images.generated.ts (${Object.keys(out).length} products).`);
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
